# permissions for end users to edit objects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: object-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-test
    app.kubernetes.io/part-of: kubebuilder-test
    app.kubernetes.io/managed-by: kustomize
  name: object-editor-role
rules:
- apiGroups:
  - syncer.sj14.github.io
  resources:
  - objects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncer.sj14.github.io
  resources:
  - objects/status
  verbs:
  - get
