---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sync-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: sync-operator
  name: sync-operator-leader-election-rolebinding
  namespace: sync-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sync-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: sync-operator
    namespace: sync-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sync-operator
    app.kubernetes.io/instance: object-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: sync-operator
  name: sync-operator-object-rolebinding
  namespace: sync-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sync-operator-object-role
subjects:
  - kind: ServiceAccount
    name: sync-operator
    namespace: sync-operator
