apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  namespace: default
data:
    key1: value1
    key2: value2 
    key3: value3
---
apiVersion: sync.sj14.github.io/v1alpha1
kind: SyncObject
metadata:
  name: syncobject-sample
spec:
  reference:
    group: "" # empty for core group
    version: v1 
    kind: ConfigMap # case-sensitive!
    name: test
    namespace: "default"
  # targetNamespaces:
  #   - kube-public
  # ignoreNamespaces:
  #   - kube-system
  # disableFinalizer: true
