name: CI
on:
  push:
    paths:
      - go.mod
      - go.sum
      - "**.go"
      - ".github/workflows/ci.yaml"
      - tools/**
      - Makefile
jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Go mod tidy
        run: | 
          go mod tidy
          git diff --exit-code
      - name: Go mod tidy (tools)
        run: | 
          go mod tidy
          git diff --exit-code
      - name: Format
        run: |
          go fmt ./...
          git diff --exit-code
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
      - name: Test
        run: |
          make test
          git diff --exit-code
